"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000
continuation_prompt = '󰶻 '
format = '''($git_branch$git_status ) ($python$nodejs)
$character'''
add_newline = true
palette = 'catppuccin_frappe'

[character] # The name of the module we are configuring is 'character'
error_symbol = '[⟫](red)'
success_symbol = '[⟫](green)'
vimcmd_symbol = '[](mauve) [⟫](green)'

[directory]
style = 'bold yellow'
truncate_to_repo = true
truncation_length = 10

[git_branch]
format = '[$symbol$branch(:$remote_branch)](sapphire)'
symbol = ' '

[git_status]
format = '[(*$deleted$modified$renamed$staged$untracked)](218)( ~( $conflicted)( $ahead_behind)( $stashed))'
ahead = '[${count}⇡](yellow)'
behind = '[${count}⇣](7)'
conflicted = '[‼](red)'
deleted = '​'
diverged = '[${behind_count}⇣](7)·[${ahead_count}⇡](yellow)'
modified = '​'
renamed = '​'
staged = '​'
stashed = '[󰆺](green)'
untracked = '​'

[nodejs]
format = '[$symbol](green)[$version](white) '
detect_extensions = []
detect_files = ['package.json']
symbol = '󰎙 '

[python]
format = '[$symbol](yellow)[$version](bold white) [\($virtualenv\)](italic bold sky) '
detect_extensions = []
detect_files = []
symbol = ' '

[palettes.catppuccin_frappe]
base = '#303446'
blue = '#8caaee'
crust = '#232634'
flamingo = '#eebebe'
green = '#a6d189'
lavender = '#babbf1'
mantle = '#292c3c'
maroon = '#ea999c'
mauve = '#ca9ee6'
overlay0 = '#737994'
overlay1 = '#838ba7'
overlay2 = '#949cbb'
peach = '#ef9f76'
pink = '#f4b8e4'
red = '#e78284'
rosewater = '#f2d5cf'
sapphire = '#85c1dc'
sky = '#99d1db'
subtext0 = '#a5adce'
subtext1 = '#b5bfe2'
surface0 = '#414559'
surface1 = '#51576d'
surface2 = '#626880'
teal = '#81c8be'
text = '#c6d0f5'
yellow = '#e5c890'
